language: node_js
node_js:
- "0.11"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - bower install
notifications:
    on_success: never
    on_failure: always